const pokemon = {
  VENUSAUR: {
    id: 3,
    species: "VENUSAUR",
    type: { type1: "GRASS", type2: "POISON" },
    stats: {
      hp: 263,
      attack: 262,
      defense: 264,
      special: 298,
      speed: 258,
    },
    attacks: ["TACKLE", "GROWL", "LEECH SEED", "VINE WHIP"],
  },
  CHARIZARD: {
    id: 6,
    species: "CHARIZARD",
    type: { type1: "FIRE", type2: "FLYING" },
    stats: {
      hp: 359,
      attack: 266,
      defense: 254,
      special: 268,
      speed: 298,
    },
    attacks: [
      "SCRATCH",
      "GROWL",
      "EMBER",
      "LEER",
      "RAGE",
      "SLASH",
      "FLAMETHROWER",
      "FIRE SPIN",
    ],
  },
  BLASTOISE: {
    id: 9,
    species: "BLASTOISE",
    type: { type1: "WATER", type2: null },
    stats: {
      hp: 361,
      attack: 264,
      defense: 298,
      special: 268,
      speed: 254,
    },
    attacks: [
      "TACKLE",
      "TAIL WHIP",
      "BUBBLE",
      "WATER GUN",
      "BITE",
      "WITHDRAW",
      "SKULL BASH",
      "HYDRO PUMP",
      "SURF",
      "STRENGTH",
    ],
  },
  RATICATE: {
    id: 20,
    species: "RATICATE",
    type: { type1: "NORMAL", type2: null },
    stats: {
      hp: 313,
      attack: 260,
      defense: 218,
      special: 198,
      speed: 292,
    },
    attacks: [
      "TACKLE",
      "TAIL WHIP",
      "QUICK ATTACK",
      "HYPER FANG",
      "SUPER FANG",
    ],
  },
  TAUROS: {
    id: 128,
    species: "TAUROS",
    type: { type1: "NORMAL", type2: null },
    stats: {
      hp: 353,
      attack: 298,
      defense: 288,
      special: 238,
      speed: 318,
    },
    attacks: [
      "TACKLE",
      "TAIL WHIP",
      "STOMP",
      "LEER",
      "RAGE",
      "TAKE DOWN",
      "STRENGTH",
    ],
  },
};

module.exports = pokemon;
